sass_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/',include('app01.urls',namespace='app01')),
    url(r"^",include('web.urls'))
]

web/urls.py
#!E:\py_virtual_env\saas_project\Scripts\python.exe
# -*- coding: utf-8 -*-

from django.conf.urls import url,include
from web.views import account,project,manage,wiki,file
from django.contrib import admin


urlpatterns = [
    url(r'^register/$',account.Register.as_view(),name='register'),
    url(r'^login/sms/$', account.LoginSms.as_view(), name='login_sms'),
    url(r'^login/$', account.Login.as_view(), name='login'),
    url(r'^send/sms/$',account.SendSms.as_view(),name='send_sms'),
    url(r'^send/sms/$',account.SendSms.as_view(),name='send_sms'),
    url(r'^image/code/$', account.ImageCode.as_view(), name='image_code'),
    url(r'^index/$', account.Index.as_view(), name='index'),
    url(r'^logout/$', account.Logout.as_view(), name='logout'),
    url(r'^project/list/$', project.Project_List.as_view(), name='project_list'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.Project_Star.as_view(), name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.Project_unStar.as_view(), name='project_unstar'),
    url(r'^manage/(?P<project_id>\d+)/', include([
        url(r'^dashboard/$', manage.Dashboard.as_view(), name='dashboard'),
        url(r'^issues/$',manage.Issues.as_view(),name='issues'),
        url(r'^statistics/$', manage.Statistics.as_view(), name='statistics'),
        url(r'^file/$', file.File.as_view(), name='file'),
        url(r'^file_post/$', file.File_Post.as_view(), name='file_post'),
        url(r'^file/cos_credential/$',file.Cos_Credential.as_view(), name='cos_credential'),
        url(r'^file/download/(?P<file_id>\d+)/$', file.File_Download.as_view(), name='file_download'),
        url(r'^wiki/$', wiki.Wiki.as_view(), name='wiki'),
        url(r'wiki/catalog/$',wiki.Wiki_Catalog.as_view(),name='wiki_catalog'),
        url(r'^wiki/add/$', wiki.Wiki_Add.as_view(), name='wiki_add'),
        url(r'^wiki/upload/$',wiki.Wiki_Upload.as_view(),name='wiki_upload'),
        url(r'^wiki/delete/(?P<wiki_id>\d+)$', wiki.Wiki_Detele.as_view(), name='wiki_delete'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)$', wiki.Wiki_Edit.as_view(), name='wiki_edit'),
        url(r'^setting/$', manage.Setting.as_view(), name='setting'),
    ],None,None))
]

web/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名',max_length=32)
    email = models.EmailField(verbose_name='邮箱',max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=32)

class PricePoliy(models.Model):
    """价格策略"""
    category_choices =(
        (1,'免费版'),
        (2,'收费版'),
        (3,'其他')
    )
    category = models.SmallIntegerField(verbose_name="收费类型",default=2,choices=category_choices)
    title = models.CharField(verbose_name='标题',max_length=10)
    #PositiveIntegerField：正整数类型
    price = models.PositiveIntegerField(verbose_name='价格')

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间')
    per_file_size = models.PositiveIntegerField(verbose_name='单项目大小（M）')
    creation_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

class Transaction(models.Model):
    """交易记录"""
    status_choices = (
        (1,'未支付'),
        (2,'已支付')
    )
    status = models.SmallIntegerField(verbose_name="订单状态",choices=status_choices)
    order = models.CharField(verbose_name='订单号',max_length=64,unique=True)
    user = models.ForeignKey(verbose_name='用户',to="UserInfo")
    price_poliy = models.ForeignKey(verbose_name='价格策略',to='PricePoliy')
    count = models.IntegerField(verbose_name='数量（年）',help_text='0表示无限期')
    price = models.IntegerField(verbose_name='实际支付价格')
    #blank 表示此处可以不填
    start_datetime = models.DateTimeField(verbose_name='开始时间',null=True,blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间',null=True,blank=True)
    creation_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class Project(models.Model):
    """项目表"""
    COLOR_CHOICES = (
        (1,'#56b8eb'),  #56b8eb
        (2,'#f28033'),  #f28033
        (3,'#ebc656'),  #ebc656
        (4,'#a2d148'),  #a2d148
        (5,'#20BFA4'),  #20BFA4
        (6,'#7461c2'),  #7461c2
        (7,'#7461c2'),  #7461c2
    )
    name = models.CharField(verbose_name='项目名称',max_length=64)
    color = models.SmallIntegerField(verbose_name='颜色',choices=COLOR_CHOICES,default=1)
    desc = models.CharField(verbose_name='项目描述',max_length=255,null=True,blank=True)
    use_space = models.IntegerField(verbose_name='项目已经使用空间',default=0)
    star = models.BooleanField(verbose_name='星标',default=False)
    join_count = models.SmallIntegerField(verbose_name='参与人数',default=1)
    creator = models.ForeignKey(verbose_name='创建者',to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    bucket = models.CharField(verbose_name='cos桶',max_length=128)
    region = models.CharField(verbose_name='cos区域',max_length=128)

class ProjectUser(models.Model):
    """项目参与者"""
    user = models.ForeignKey(verbose_name='用户',to='UserInfo')
    project = models.ForeignKey(verbose_name='项目名称',to='Project')
    star = models.BooleanField(verbose_name='星标',default=False)
    join_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)

class Wiki(models.Model):
    project = models.ForeignKey(verbose_name='项目',to='Project')
    title = models.CharField(verbose_name='标题',max_length=32)
    content = models.TextField(verbose_name='内容')
    depth = models.IntegerField(verbose_name='深度',default=1)
    #子关联
    parent = models.ForeignKey(verbose_name='父文章',to='self',null=True, blank=True,related_name='children')

class FileRepository(models.Model):
    """  文件库  """
    project = models.ForeignKey(verbose_name="项目名称",to='project')
    file_type_choices = (
        (1,"文件"),
        (2,"文件夹"),
    )
    file_type = models.SmallIntegerField(verbose_name="类型",choices=file_type_choices)
    name = models.CharField(verbose_name="文件夹名称",max_length=64,help_text="文件/文件夹")
    key = models.CharField(verbose_name="文件存储存在COS中的KEY",max_length=128,null=True)
    file_size = models.IntegerField(verbose_name="文件大小",null=True,blank=True)
    file_path = models.CharField(verbose_name="文件路径",max_length=255,null=True,blank=True)
    parent = models.ForeignKey(verbose_name="父目录",to="self",related_name="child",null=True,blank=True)
    update_user = models.ForeignKey(verbose_name="最近更新者",to="UserInfo")
    update_time = models.DateTimeField(verbose_name="最近更新的时间",auto_now=True)

web/forms/wiki.py
#!E:\py_virtual_env\saas_project\Scripts\python.exe
# -*- coding: utf-8 -*-
from django import forms
from web import models
from django.core.validators import RegexValidator,ValidationError
from django.core.exceptions import ValidationError
from web.forms.account import BootStrapForm

class Wiki_Model_Form(BootStrapForm,forms.ModelForm):
    class Meta:
        model = models.Wiki
        exclude = ['project','depth']

    #找到想要的字段把他绑定显示的数据重置
    # 数据 = 去数据库中获取 当前项目所有的wiki标题
    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        total_data_list = [("","请选择")]
        data_list = models.Wiki.objects.filter(project=request.tracer.project).values_list('id','title')
        total_data_list.extend(data_list)

        self.fields['parent'].choices = total_data_list

web/views/file.py
#!E:\py_virtual_env\saas_project\Scripts\python.exe
# -*- coding: utf-8 -*-
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from web.forms.file import CreateFolderForm,FileModelForm
from rest_framework.views import APIView
from web import models
from utils.tencent.cos import credential,delete_file,delete_file_list
from django.urls import reverse
import requests
import json

class File(APIView):

    def get(self,request,project_id):
        parent_object = None
        """
        获取所有的文件和文件夹对象
        :param request:
        :param project_id:
        :return:
        """
        folder_id= request.GET.get("folder_id","")
        dir_list = []
        form = CreateFolderForm(request,parent_object)
        #判断URL是否有folder_id参数
        #如果没有则访问根目录
        #如果有则访问对应ID的目录
        if not folder_id:
            folder_object = None
            file_object_list = models.FileRepository.objects.filter(parent=None).order_by('-file_type')
        else:
            parent_object = models.FileRepository.objects.filter(id=folder_id,file_type=2).first()
            file_object_list = models.FileRepository.objects.filter(parent=parent_object)
            folder_object = parent_object
            row_object = parent_object
            while row_object:
                dir_list.insert(0,row_object)
                row_object = row_object.parent
        return render(request,'file.html',
                      {
                          'form':form,
                          'file_object_list':file_object_list,
                          'folder_object':folder_object,
                          'dir_list':dir_list
                      })

    def post(self,request,project_id):
        parent_object = None
        fid = request.POST.get('fid', '')
        if fid.isdecimal():
            edit_object = models.FileRepository.objects.filter(id=int(fid), file_type=2,
                                                               project=request.tracer.project).first()
        if edit_object:
            form = CreateFolderForm(request, parent_object, data=request.POST, instance=edit_object)
        else:
            form = CreateFolderForm(request,data=request.POST)
        parent_object = None
        folder_id = request.GET.get('folder_id')
        print(folder_id)
        if folder_id:
            parent_object = models.FileRepository.objects.filter(id=folder_id,file_type=2,project=request.tracer.project).first()
        if form.is_valid():
            form.instance.project = request.tracer.project
            form.instance.file_type=2
            form.instance.update_user=request.tracer.user
            form.instance.parent= parent_object
            form.save()
            return JsonResponse({'status':True,'error':None})
        else:
            return JsonResponse({'status':False,'error':form.errors})

    def delete(self,request,project_id):
        """ 删除文件 """
        fid = request.data.get('fid')

        # 删除数据库中的 文件 & 文件夹 （级联删除）
        delete_object = models.FileRepository.objects.filter(id=fid, project=request.tracer.project).first()
        if delete_object.file_type == 1:
            # 删除文件，将容量还给当前项目的已使用空间
            request.tracer.project.use_space -= delete_object.file_size
            request.tracer.project.save()

            # cos中删除文件
            delete_file(request.tracer.project.bucket, request.tracer.project.region, delete_object.key)

            # 在数据库中删除当前文件
            delete_object.delete()

            return JsonResponse({'status': True})

        # 删除文件夹（找到文件夹下所有的文件->数据库文件删除、cos文件删除、项目已使用空间容量还回去）
        # delete_object
        # 找他下面的 文件和文件夹
        # models.FileRepository.objects.filter(parent=delete_object) # 文件 删除；文件夹 继续向里差

        total_size = 0
        key_list = []

        folder_list = [delete_object, ]
        for folder in folder_list:
            child_list = models.FileRepository.objects.filter(project=request.tracer.project, parent=folder).order_by(
                '-file_type')
            for child in child_list:
                if child.file_type == 2:
                    folder_list.append(child)
                else:
                    # 文件大小汇总
                    total_size += child.file_size

                    # 删除文件
                    key_list.append({"Key": child.key})

        # cos 批量删除文件
        if key_list:
            delete_file_list(request.tracer.project.bucket, request.tracer.project.region, key_list)

        # 归还容量
        if total_size:
            request.tracer.project.use_space -= total_size
            request.tracer.project.save()

        # 删除数据库中的文件
        delete_object.delete()
        return JsonResponse({'status': True})

class File_Post(APIView):

    def post(self,request,project_id):
        """ 已上传成功的文件写入到数据 """
        """
        name: fileName,
        key: key,
        file_size: fileSize,
        parent: CURRENT_FOLDER_ID,
        # etag: data.ETag,
        file_path: data.Location
        """

        # 根据key再去cos获取文件Etag和"db7c0d83e50474f934fd4ddf059406e5"

        print(request.POST)
        # 把获取到的数据写入数据库即可
        form = FileModelForm(request, data=request.POST)
        if form.is_valid():
            # 通过ModelForm.save存储到数据库中的数据返回的isntance对象，无法通过get_xx_display获取choice的中文
            # form.instance.file_type = 1
            # form.update_user = request.tracer.user
            # instance = form.save() # 添加成功之后，获取到新添加的那个对象（instance.id,instance.name,instance.file_type,instace.get_file_type_display()

            # 校验通过：数据写入到数据库
            data_dict = form.cleaned_data
            data_dict.pop('etag')
            data_dict.update({'project': request.tracer.project, 'file_type': 1, 'update_user': request.tracer.user})
            instance = models.FileRepository.objects.create(**data_dict)
            # 项目的已使用空间：更新 (data_dict['file_size'])
            request.tracer.project.use_space += data_dict['file_size']
            request.tracer.project.save()
            print(instance.update_time)
            result = {
                'id': instance.id,
                'name': instance.name,
                'file_size': instance.file_size,
                'username': instance.update_user.username,
                'datetime': instance.update_time.strftime('%Y{y}%m{m}%d{d} %H{h}%M{f}%S{s}').format(y='年', m='月', d='日', h='时', f='分', s='秒'),
                'download_url': reverse('file_download', kwargs={"project_id": project_id, 'file_id': instance.id})
                # 'file_type': instance.get_file_type_display()
            }
            return JsonResponse({'status': True, 'data': result})
        print(form.errors)
        return JsonResponse({'status': False, 'data': "文件错误"})

class File_Download(APIView):
    def get(self,request,project_id,file_id):
        file_object = models.FileRepository.objects.filter(id=file_id, project_id=project_id).first()
        res = requests.get(file_object.file_path)

        # 文件分块处理（适用于大文件）     @孙歆尧
        data = res.iter_content()

        # 设置content_type=application/octet-stream 用于提示下载框        @孙歆尧
        response = HttpResponse(data, content_type="application/octet-stream")
        from django.utils.encoding import escape_uri_path

        # 设置响应头：中文件文件名转义      @王洋
        response['Content-Disposition'] = "attachment; filename={};".format(escape_uri_path(file_object.name))
        return response


class Cos_Credential(APIView):
    def get(self,requwst,project_id):
        pass

    def post(self, request, project_id):
        """ 获取cos上传临时凭证 """
        per_file_limit = request.tracer.price_poliy.per_file_size * 1024 * 1024
        total_file_limit = request.tracer.price_poliy.project_space * 1024 * 1024 * 1024

        total_size = 0
        file_list = json.loads(request.body.decode('utf-8'))
        for item in file_list:
            # 文件的字节大小 item['size'] = B
            # 单文件限制的大小 M
            # 超出限制
            if item['size'] > per_file_limit:
                msg = "单文件超出限制（最大{}M），文件：{}，请升级套餐。".format(request.tracer.price_policy.per_file_size, item['name'])
                return JsonResponse({'status': False, 'error': msg})
            total_size += item['size']

            # 做容量限制：单文件 & 总容量

        # 总容量进行限制
        # request.tracer.price_poliy.project_space  # 项目的允许的空间
        # request.tracer.project.use_space # 项目已使用的空间
        if request.tracer.project.use_space + total_size > total_file_limit:
            return JsonResponse({'status': False, 'error': "容量超过限制，请升级套餐。"})

        data_dict = credential(request.tracer.project.bucket, request.tracer.project.region)
        return JsonResponse({'status': True, 'data': data_dict})

web/templates/dashboard.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>概览</h1>
{% endblock %}

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block tiele %}用户主页{% endblock %}

{% block css %}
    <style>
        img{
            width: 100%;
        }
    </style>
{% endblock %}
    
{% block content %}
    <img src="{% static "img/index/index-1.png" %}">
    <img src="{% static "img/index/index-2.png" %}">
    <img src="{% static "img/index/index-3.png" %}">
    <img src="{% static "img/index/index-4.png" %}">
{% endblock %}

{% block js %}
{% endblock %}

web/templates/issues.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>问题</h1>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block tiele %}用户注册{% endblock %}

{% block css %}
    <link rel="stylesheet" href= "{% static 'css/account.css' %}" />
    <style>
        .error-msg{
            color: red;
            position: absolute;/*使用绝对定位，防止挤压后面的标签*/
            font-size: 11px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户短信登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for filed in form %}
                {% if filed.name == 'code' %}
                    <div class="form-group">
                        <label for={{ filed.id_for_label }}.>{{ filed.label }}</label>
                        <div class="clearfix">
                            <div class="col-md-7" style="padding: 0px">{{ filed }}
                            <span class="error-msg">{{ filed.errors.0 }}</span>
                            </div>
                            <div class="col-md-5" ><input type="button" class="btn btn-default" id="btn_sms" value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for={{ filed.id_for_label }}.>{{ filed.label }}</label>
                        {{ filed }}
                        <span class="error-msg" >{{ filed.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right">
                    <a href="{% url "login" %}">账号密码登录</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
<script>
    $(function () {
        bindClickBtnSms()
        bindClickBtnSubmit()
    })
    /*
    点击获取验证码
    */
    function bindClickBtnSms(){
         $('#btn_sms').click(function () {
             $('.error-msg').empty()
            var mobile_phone = $('#id_mobile_phone').val()
            $.ajax({
                url:'/send/sms/',
                data:{'mobile_phone':mobile_phone,'tpl':'login'},
                type:'GET',
                dataType:"JSON",
                success:function (res) {
                    if (res.status == true){
                        sendSmsRemind()
                    }else {
                        console.log(res)//{''status':False,'error':{'mobile_phone':['请输入一个有效值。']}}
                        $.each(res.error,function (key,value) {
                            $('#id_'+key).next().text(value[0]);
                        })
                    }
                }
                }
            )
            }
        )
    }
    /*
    点击提交（登录）
    */
    function bindClickBtnSubmit() {
        $('#btnSubmit').click(function () {
            /* 清空所有错误信息 */
            $('.error-msg').empty()
            $.ajax({
                url: "{% url 'login_sms' %}",
                type: 'POST',
                data:$('#smsForm').serialize(), //Form中的所有字段+数据+csrf token
                dataType: 'JSON',
                success:function (res) {
                    if (res.status == true){
                        location.href = res.url
                    }else {
                        $.each(res.error,function (key,value) {
                            $('#id_'+key).next().text(value[0]);
                        })
                    }
                }
            })
        })
    }
    function sendSmsRemind() {
        var SendSms = $('#btn_sms')
        SendSms.prop('disabled',true)//禁用
        //每隔1000毫秒运行一次
        var time = 60
        var obj = setInterval(function(){
            time = time -1
            SendSms.val(time+'秒重新发送')
            if (time < 1){
                clearInterval(obj);
                SendSms.val('点击获取验证码').prop('disabled',false)
            }
        },1000)
        //关闭定时器
    }
</script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}

{% block css %}
    <style>
        .project {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            {#Flex是Flexible Box的缩写，#}
            {#意为"弹性布局"，用来为盒状模型提供最大的灵活性。#}
            {#设为Flex布局以后，子元素的float、#}
            {#clear和vertical-align属性将失效。#}
            flex-direction: row;
            {#flex-direction:row; 沿水平主轴让元素从左向右排列#}
            justify-content: left;
            {#justify-content 元素在主轴（页面）上的排列#}
            {#justify-content : center;元素在主轴（页面）上居中排列#}
            align-items: flex-start;
            {#align-items : flex-start; 弹性盒子元素的侧轴（纵轴）起始位置的边界紧靠住该行的侧轴起始边界（靠上对齐）。#}
            flex-wrap: wrap;
            {#flex-wrap: wrap; 元素换行,比如：一个div宽度100%，设置此属性，第二个div就在第二行了；#}
        }

        .panel-body > .item {
            border-radius: 6px;
            {#它表示元素四个方向的圆角大小都是6px，即每个圆角的“水平半径”和“垂直半半径”都设置为6px；#}
            width: 228px;
            border: 1px solid #dddddd;
            {#border描边#}
            margin: 5px 10px;
            {#margin：每个div的左右边距#}
        }

        {#hover:把鼠标放在div上显示的效果#}
        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            {#justify-content:水平方向的位置#}
            align-items: center;
            {#align-items：垂直方向的位置#}
            border-top-left-radius: 6px;
            {#border-top-left-radius：左上圆角#}
            border-top-right-radius: 6px;
            {#border-top-right-radius：右上圆角#}
            font-size: 30px;
            text-decoration: none ;
            {#text-decoration:文本下划线设置#}
        }

        .panel-body > .item > .info {
            padding: 10px 10px;
            {#padding：上下边距10#}
            display: flex;
            justify-content: space-between;
            {#justify-content : space-between;元素在主轴（页面）上左右两端或者上下两端开始排列#}
            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration:none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <a class="btn btn-primary " data-toggle="modal" data-target="#addModal"><i class="fa fa-plus-circle"></i>新建项目</a>
        <div class="panel panel-default project">
          <div class="panel-heading"><i class="fa fa-star" style="color: #f0ad4e" aria-hidden="true" ></i> 星标</div>
          <div class="panel-body">
            {% for item in project_dict.star %}
                <div class="item">
                        <a href="{% url 'dashboard' project_id=item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
            {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的</div>
          <div class="panel-body">
            {% for item in project_dict.my %}
                <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type="my" project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
            {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的</div>
          <div class="panel-body">
            {% for item in project_dict.join %}
                <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type="join" project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
            {% endfor %}
          </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">新建项目</h4>
          </div>
          <div class="modal-body">
            <form id="addForm">
                {% csrf_token %}
                {% for fied in form %}
                    <div class="form-group">
                        <label for="{{fied.id_for_label}}">{{fied.label}}</label>
                        {{ fied }}
                        <span class="error-msg">{{ fied.errors.0 }}</span>
                      </div>
                {% endfor %}
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            <button id="btnSubmit" type="button" class="btn btn-primary">确 定</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block js %}
    <script>
     $(function () {
        bindbtnSubmit()
     })
    function bindbtnSubmit() {
        $('#btnSubmit').click(function () {
            $.ajax({
                url:"{% url 'project_list' %}",
                type:'POST',
                dataType:'JSON',
                data:$('#addForm').serialize(),
                success:function (res) {
                    if (res.status == true){
                        location.reload()
                    }else {
                        console.log(res)
                        $.each(res.error,function (key,value) {
                            $('#id_'+key).next().text(value[0]);
                        })
                    }
                }
            })
        })
    }
    </script>
{% endblock %}

web/templates/setting.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>配置</h1>
{% endblock %}

web/templates/statistics.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>统计</h1>
{% endblock %}